services:
  mysql:
    image: mysql:8.0
    container_name: aramis_mysql
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - TZ=America/Sao_Paulo
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init:/docker-entrypoint-initdb.d
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: aramis_phpmyadmin
    restart: unless-stopped
    env_file: .env
    environment:
      - PMA_HOST=mysql
      - PMA_USER=${MYSQL_USER}
      - PMA_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
    - mysql


  backend:
    build: ./backend
    container_name: aramis_backend
    restart: unless-stopped
    env_file: .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - ./backend:/main
    ports:
      - "8000:8000"
    depends_on:
      - mysql

  frontend:
    build: ./frontend
    container_name: aramis_frontend
    restart: unless-stopped
    env_file: .env
    environment:
      - BACKEND_URL=${BACKEND_URL}
    volumes:
      - ./frontend:/app
    ports:
      - "8501:8501"
    depends_on:
      - backend

volumes:
  mysql_data:
